#!/bin/sh

# prereqs: local couchdb is running, blueproxy in PATH

DBNAME=phy-f2f-acc-db
echo DBNAME: $DBNAME

MYBTADDR=$(sudo hciconfig hci0 | awk '/BD Address/ {print $3}')
echo MYBTADDR: $MYBTADDR

sync_with_known_nodes () {
    cat known_nodes.txt | while read btaddr name; do
        if [ "$btaddr" != "$MYBTADDR" ]; then
            echo ./couchdb-repli $btaddr $DBNAME "# $name"
            ./couchdb-repli $btaddr $DBNAME
        fi
    done
}

sync_with_all_nodes () { # requires bluetooth visibility
    for btaddr in $(hcitool scan | awk '!/^Scanning/ {print $1}'); do
        if [ "$btaddr" != "$MYBTADDR" ]; then
            echo ./couchdb-repli $btaddr $DBNAME
            ./couchdb-repli $btaddr $DBNAME
        fi
    done
}

trap "kill -HUP -$$" EXIT # kill all child processes on exit

blueproxy -p 5984 &
(while true; do socat -d -d tcp-listen:20000,reuseaddr tcp-listen:20001,reuseaddr; sleep 1; done) &

sleep 3

while true; do
    echo `date`: start sync

    #sync_with_known_nodes
    sync_with_all_nodes

    echo `date`: end sync
    sleep 1800
done
